### ISSUE TITLE
Small Portable Text color issues

### ISSUE THREAD

**Issue by jenniferaadams** [cositehq/sanity-plugin-simpler-color-input#13]
I love the plugin and how easy it was to implement and use! I have all my custom colors in a list to choose from and it's great. 

I just have a couple of issues:

1. If I want to change portable text to white (which is the main color I use other than standard gray/black), you can only see it in Sanity if you switch to dark mode. This isn't a huge deal, as it's still workable, but I need to then explain this to the marketing team and anyone new who is going to try to use it. Could there be a better preview (highlighting maybe?) for white portable text?

White portable text in Sanity's light mode:
![portable text white](https://github.com/user-attachments/assets/7a4be7ec-aaf1-4169-bd10-eb45378560b9)

2. I think this may have more to do with the way portable text works and is stored, but if I want to change the color of any of the lists (bullets or numbered), it does not change the color of the bullets/numbers. Also, if you try to highlight and change the color of a whole list (more than one element at a time), it does not work very well. I will get part of one, and then it won't do the next one or vice versa. I got around this by always selecting and putting a color on each list element individually, but again, I need to explain this to my marketing team. Also, when I am trying to then display the list on my site, the text would be the correct color, but not the bullets/numbers. I had to go in and dig through some props and add some css that took a while to get working.  

Had to do this in on my portable text block to get the bullet/numbers to use the same color. Maybe this will help someone else out:

![bullet colors](https://github.com/user-attachments/assets/cd8c6a30-d43c-449d-8e64-8f539ae32950)

**Comment by AlyssaKirstine** [comment]
Hi @jenniferaadams thank you for using the plugin! I'm so glad to hear it's been easy to use.

1. I took a look at how the popular document editors handle this and it looks like they all do so in the same way I am in the plugin! I don't want to highlight the text when it's white since that will conflict with the behavior of the `highlightColor` annotation and over-complicate the plugin I'm afraid. I'm not sure what an elegant solution would be apart from this and considering this is pretty standard behavior, I'm going to leave this as is. Perhaps you could [customize your Sanity studio theme](https://www.sanity.io/docs/theming) and change the background color to be slightly off-white to help address this issue on your team?
2. There are 3 things to consider here-
     1. **Being able to highlight and color multiple bullets.** Unfortunately this is a limitation of the portable text schema itself 😕. You have to apply annotations for each block in a document. I know it's inconvenient.
     2. **Styling the bullet color in the portable text editor itself.** I did look into styling this and figured out how to get it working on the plugin side of things so it's possible. I am unsure about implementing this globally in the plugin, however, since users will have different preferences and I'd rather keep the plugin open to individual user customization rather than making it too opinionated. An example of this preference and nuance could be in the case of the words in the list item being different colors. If that's the case, if the whole text is pink, okay sure maybe we'd want the bullet to be pink, but what if only one of the words is pink? What color should the bullet be then? Here's a photo of what I mean:
     ![image](https://github.com/user-attachments/assets/2b66b391-cb2a-4821-8879-d021aee840c2)
Ultimately,  I don't know that I want to force a specific bullet color but I'd rather leave it up to individuals to configure on a case-by-case basis.
     3. **Styling the bullet color on the frontend page itself.** For the same reasons as above and different individual/team preferences, I don't want to force this either. This is something that I can't do on the plugin side itself and needs configured by the individual on the frontend anyways. Your approach is a good one. You might also be able to use the `:has` CSS pseudo-class to accomplish this.
     
I appreciate your feedback and efforts to help make the plugin better. Even though I couldn't address anything on the plugin end for this, please keep sharing any feedback and feature requests you have as they come up. Happy coloring :)
